######################################################################################################
# API 서버 - Dev 환경 정보
######################################################################################################
allowed_origins: ${ALLOWED_ORIGINS}

#-----------------------------------------------------------------------------------------------------
# spring
#-----------------------------------------------------------------------------------------------------
spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    dialect: ${SPRING_DATASOURCE_DIALECT}

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}